-- Create shortcuts table
CREATE TABLE shortcuts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shortform VARCHAR(10) NOT NULL,
    brand_id BIGINT NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(shortform),
    UNIQUE(brand_id)
);

-- Add RLS policies
ALTER TABLE shortcuts ENABLE ROW LEVEL SECURITY;

-- Create open access policy
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON shortcuts;
DROP POLICY IF EXISTS "Enable insert access for authenticated users" ON shortcuts;
DROP POLICY IF EXISTS "Enable update access for authenticated users" ON shortcuts;
DROP POLICY IF EXISTS "Enable delete access for authenticated users" ON shortcuts;

CREATE POLICY "Allow all access to shortcuts"
    ON shortcuts FOR ALL
    USING (true)
    WITH CHECK (true);

-- Create updated_at function
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for updated_at
CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON shortcuts
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at(); 